alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: twitter-bot
region: nyc
services:
- http_port: 8080
  image:
    registry_type: DOCR
    repository: twitter-bot
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: twitter-bot
  routes:
  - path: /
