name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: CICD

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Generate coverage report
      env:
        DB_CLUSTER_ID: ${{ secrets.DB_CLUSTER_ID }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DATBASE_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
           go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0

