name: Linting

on:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  pull-requests: read

jobs:

  golangci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.18]
    name: lint

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patchversion.
          version: v1.29
          # Optional: golangci-lint command line arguments.
          # args: --enable-all

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
